### ISSUE TITLE
Cannot run the demo: missing files and old dependencies

### ISSUE THREAD

**Issue by ialhashim** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#1]
I am having a hard time running the demo due to the following reasons:

- This module seems to be missing `import models.modules.STVSR as STVSR`
- This module also seems to be missing `Sakuya_arch_test`
- The DCNv2 module is not compatible with newer GPUs, I can't compile it

**Comment by andorxornot** [comment]
confirm

**Comment by zychen-ustc** [comment]
I have updated the code and fixed your first two problems. Sorry for any inconvenience caused.

For DCNv2 module, I tested on both RTX A4000 and RTX 2080Ti, and the installations are successful. The module works well for pytorch 1.4.0 & torchvision 0.5.0. It seems that the implementation does not support pytorch >= 1.5.0.

**Comment by ialhashim** [comment]
I still had to modify the 'demo.py' file by changing `Sakuya_arch2` to `Sakuya_arch` and also use hardware older than 3080.. so in Colab this seems to be working

![image](https://user-images.githubusercontent.com/2434978/173637544-bc4c10fc-b1b8-495e-a7eb-943ec67c216b.png)
