### ISSUE TITLE
training cost

### ISSUE THREAD

**Issue by baiyang4** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#4]
Hi there,

Thanks for your great work. Can I ask what is the training time, and GPU to train the model.

BW

**Comment by zychen-ustc** [comment]
We use 4 RTX 2080Ti for training and it takes about 160 hours for the whole training process.

**Comment by Eunjnnn** [comment]
@zychen-ustc 
Thank you for the great work!! I wonder whether you used DistributedDataParallel or just DataParallel while using 4 gpu?
