### ISSUE TITLE
Unknown CUDA arch 8.0 or GPU not supported in DCNv2 setup

### ISSUE THREAD

**Issue by barakmam** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#5]
I did the following int your installation guid.
It seems to require cuda arch 8.0 but this torch version (1.4.0) doesn't support that version.

In cpp_extension.py there is not 8.0 valid arch for cuda. 

Any help?

Thanks in advance. 
![image](https://user-images.githubusercontent.com/57372254/182131307-ef1f565e-f015-457a-9951-48e38f31079c.png)

**Comment by zychen-ustc** [comment]
Yes. It seems CUDA arch 8.0 is too old. Maybe try a newer version of it.

**Comment by yuanlinwang** [comment]
我运行时遇到的两个问题解决方案：
https://blog.csdn.net/qq_37346140/article/details/127684795
https://github.com/CharlesShang/DCNv2/issues/14

**Comment by jakobtroidl** [comment]
I think I solved this problem using a [new version](https://github.com/lucasjinreal/DCNv2_latest) of DCNv2. I am using `Python 3.8`, and `Torch 1.11` and `CUDA 11.3`on `Ubuntu`. Here's how to reproduce my setup. 

Create a VINR conda environment.
```
conda create -n vinr python=3.8
conda activate vinr
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```

Initialize and build the DCNv2 submodule.
```
git submodule add https://github.com/lucasjinreal/DCNv2_latest ./models/modules/
git submodule init
cd models/modules/DCNv2_latest
python3 setup.py build develop
cd ../..
```

Run demo
```
python demo.py --space_scale=4 --time_scale=8 --data_path="YOUR DATA"
```
