### ISSUE TITLE
Is it the last release that I can train the model?

### ISSUE THREAD

**Issue by Ree1s** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#6]
Thanks for sharing this interesting code. 
Can you show the processing code of data preparation? I follow TMNet to prepare it but it seems different with the format of this dataloader.

**Comment by zychen-ustc** [comment]
I updated the codebase and fixed several bugs. I am sure you can easily train our model from scratch now! Sorry for the inconvenience caused.
