### ISSUE TITLE
High resolution model

### ISSUE THREAD

**Issue by surfingnirvana** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#8]
Is there any way i can try to upscale from higher resolution? The resolution of this model is 160x90 pix to 4x.
Is it possible to start on a higher resolution like 960x640?

**Comment by zychen-ustc** [comment]
You can use images with any resolution as the input and set any up-sampling scales. However, I am afraid input images with too large resolutions would cause the CUDA OUT OF MEMORY error.

**Comment by noobtoob4lyfe** [comment]
Unfortunately this is not very practical if it cannot take at lest 1080p input footage.
