### ISSUE TITLE
Testing scripts of VideoINR

### ISSUE THREAD

**Issue by zhangxydlut** [Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution#9]
Thanks for your great job!
Could you provide the scripts for testing, which can reproduce the performances (PSNR and SSIM) reported in the paper?
It would be very helpful. Thanks again!

**Comment by sichun233746** [comment]
Hello @zhangxydlut ,

Did you get the performance similar to the numbers in VideoINR paper ?
I'm trying to reproduce those numbers.
Can we discuss?

**Comment by hzwer** [comment]
Do you have any experience in reproducing Table 1 of the paper?

**Comment by sichun233746** [comment]
> Do you have any experience in reproducing Table 1 of the paper?

@hzwer Yes, I've successfully re-produced the results.

**Comment by hzwer** [comment]
@sichun233746 I test the pretrained models, but get little higher y-channel PSNR than table 1 (Both Adobe240fps and Gopro). When calculating on rgb space. get about 1dB lower. Would you mind giving me some hints?

I follow the description of papre, "image sequences extracted from videos in the datasets are split into groups of 9-frame video clips. We feed the 1st and 9th frames down-sampled by scale ×4 in each clip into models to generate 9 high-resolution frames from 1st to 9th."
Paper Table 1 Gopro: 30.26dB, 29.41dB
My Gopro test: 30.95dB, 29.77dB (y channel)
My Gopro test: 28.2dB, 29.2dB (rgb channel)

**Comment by sichun233746** [comment]
@hzwer Actually, I get little lower y-channel PSNR than table1.

I think you should only calculate PSNR for 1st to 8th frame, since the 9th frame will be the 1st frame in the next sequence.
Did you calculate PSNR value like this?

**Comment by hzwer** [comment]
@sichun233746 Thank you so much, I think it's reasonable. I will contact the author to check this.

**Comment by hzwer** [comment]
Thank you for this important suggestion again @sichun233746 , I have tested about 1/3 gopro images yet and got very close numbers as table 1.

**Comment by sichun233746** [comment]
@hzwer FYI, the Y channel PSNR I got for Gopro dataset is 30.08.

**Comment by xiximelon** [comment]
@sichun233746 hello!sorry to bother you! 
I'd like to know whether the pretrained model provided by the author can be used for testing? And could you please provide a best checkpoints.pth ?

**Comment by ROTTK** [comment]
@hzwer @sichun233746 
Hello guys, could you please share your experience in testing the pre-trained model on the Gopro dataset?
I'm trying to use the pre-trained model to input low-resolution 1st and 5th frames and generate high-resolution 2nd to 4th frames, but the frames I'm generating are only 20dB on the PSNR.
